name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        # Esto instala tus librerías definidas en pyproject.toml
        run: poetry install 

      - name: Run tests
        # Esto ejecuta tus tests usando el entorno virtual de poetry
        run: poetry run pytest tests/